# SPDX-License-Identifier: GPL-2.0
# Custom misc drivers — add these lines to the main drivers/misc/Makefile
obj-$(CONFIG_MIGRATION_TRACER) += migration_tracer.o
obj-$(CONFIG_KWORKER_TRACER)   += kworker_tracer.o
obj-$(CONFIG_BOOT_KPI_TRACER)  += boot_kpi.o
obj-$(CONFIG_MTHP_MONITOR)     += mthp_monitor/
obj-$(CONFIG_MTHP_BESTFIT)     += mthp_bestfit/
